import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Processor} from "../components/Processor";
import {useScore} from "../contexts/ScoreContext";

const Home: NextPage = () => {
    const { score } = useScore();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">why dou!</a>
        </h1>

        <p className={styles.description}>
          Get started by copying your text in the box below
        </p>

        <Processor/>



          { score > 0 && <h2 className={styles.title}>
              Score: {score}
          </h2>}

          <p>
              Russland hat die Verantwortung für den Angriff auf den Hafen Odessa eingeräumt. Bei dem Beschuss des wichtigsten ukrainischen Schwarzmeerhafens am Samstag seien ein ukrainisches Kriegsschiff sowie ein Lager mit von den USA gelieferten Harpoon-Raketen zerstört worden, teilte die Sprecherin des russischen Außenministeriums, Marija Sacharowa, mit. Nach ukrainischen Angaben wurden bei dem Angriff auch Hafenanlagen getroffen, darunter auch Anlagen zur Verarbeitung von Getreide. Der Angriff war nur einen Tag später erfolgt, nachdem die Regierungen in Moskau und Kiew einem Abkommen über den Export von blockiertem ukrainischem Getreide zugestimmt hatten.
          </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
