import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Processor} from "../components/Processor";
import {useScore} from "../contexts/ScoreContext";

const Home: NextPage = () => {
    const { score } = useScore();

  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-6xl font-normal leading-normal mt-2 mb-2 text-slate-800 text-center">
          Welcome to <a href="https://nextjs.org">why dou!</a>
        </h1>

        <Processor/>



          { score > 0 && <h2 className={styles.title}>
              Score: {score}
          </h2>}

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
